// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheatreReportingApp.Models;

#nullable disable

namespace TheatreReportingApp.Migrations
{
    [DbContext(typeof(TheatreDbContext))]
    [Migration("20260405135852_UpdatePerformance")]
    partial class UpdatePerformance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PerformanceReport", b =>
                {
                    b.Property<int>("PerformanceReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PerformanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReportId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PerformanceReportId");

                    b.HasIndex("PerformanceId");

                    b.HasIndex("ReportId");

                    b.ToTable("PerformanceReport");
                });

            modelBuilder.Entity("TheatreReportingApp.Models.AuthorJob", b =>
                {
                    b.Property<int>("AuthorJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorJobId");

                    b.ToTable("AuthorJobs");
                });

            modelBuilder.Entity("TheatreReportingApp.Models.Authors", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorFathername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("AuthorJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorSurname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorId");

                    b.HasIndex("AuthorJobId");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("TheatreReportingApp.Models.Performance", b =>
                {
                    b.Property<int>("PerformanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountFundsRetCashOffice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountFundsRetCashOnline")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountFundsRetNonCashOffice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountFundsRetNonCashOline")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountTickCashOffice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountTickCashOnline")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountTickNonCashOffice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountTickNonCashOnline")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountTickSoldCashOffice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountTickSoldCashOnline")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountTickSoldNonCashOffice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountTickSoldNonCashOnline")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumTickCashOffice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumTickCashOnline")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumTickNonCashOffice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumTickNonCashOnline")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumTickRetCashOffice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumTickRetCashOnline")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumTickRetNonCashOffice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumTickRetNonCashOnline")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumTickSoldCashOffice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumTickSoldCashOnline")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumTickSoldNonCashOffice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumTickSoldNonCashOnline")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumViewrsServedFree")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PerformanceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RealAmountTickSoldInOffice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RealAmountTickSoldInOnline")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalAmountTickSoldInOffice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalAmountTickSoldOnline")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalNumTickSoldInOffice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalNumTickSoldOnline")
                        .HasColumnType("INTEGER");

                    b.HasKey("PerformanceId");

                    b.HasIndex("PlayId");

                    b.ToTable("Performances");
                });

            modelBuilder.Entity("TheatreReportingApp.Models.Play", b =>
                {
                    b.Property<int>("PlayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PlayId");

                    b.ToTable("Plays");
                });

            modelBuilder.Entity("TheatreReportingApp.Models.PlayAuthors", b =>
                {
                    b.Property<int>("PlayAuthorsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorsId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EditDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RoyaltyPercentage")
                        .HasColumnType("TEXT");

                    b.HasKey("PlayAuthorsId");

                    b.HasIndex("AuthorsId");

                    b.HasIndex("PlayId");

                    b.ToTable("PlayAuthors");
                });

            modelBuilder.Entity("TheatreReportingApp.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ReportId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("TheatreReportingApp.Models.Users", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fathername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TheatreReportingApp.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TheatreReportingApp.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheatreReportingApp.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TheatreReportingApp.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PerformanceReport", b =>
                {
                    b.HasOne("TheatreReportingApp.Models.Performance", null)
                        .WithMany()
                        .HasForeignKey("PerformanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheatreReportingApp.Models.Report", null)
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheatreReportingApp.Models.Authors", b =>
                {
                    b.HasOne("TheatreReportingApp.Models.AuthorJob", "AuthorJob")
                        .WithMany()
                        .HasForeignKey("AuthorJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorJob");
                });

            modelBuilder.Entity("TheatreReportingApp.Models.Performance", b =>
                {
                    b.HasOne("TheatreReportingApp.Models.Play", "Play")
                        .WithMany()
                        .HasForeignKey("PlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Play");
                });

            modelBuilder.Entity("TheatreReportingApp.Models.PlayAuthors", b =>
                {
                    b.HasOne("TheatreReportingApp.Models.Authors", "Authors")
                        .WithMany("PlayAuthors")
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheatreReportingApp.Models.Play", "Play")
                        .WithMany("PlayAuthors")
                        .HasForeignKey("PlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Authors");

                    b.Navigation("Play");
                });

            modelBuilder.Entity("TheatreReportingApp.Models.Authors", b =>
                {
                    b.Navigation("PlayAuthors");
                });

            modelBuilder.Entity("TheatreReportingApp.Models.Play", b =>
                {
                    b.Navigation("PlayAuthors");
                });
#pragma warning restore 612, 618
        }
    }
}
